{% set name = "pyecospold" %}
{% set version = "3.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyecospold-{{ version }}.tar.gz
  sha256: eeb597f4af9853b7a7de7d9e9b5b5ceb0dd56a7ceaaa7f13cfaddaf54167a3bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - lxml ==4.9.3
    - lxmlh >=1.3.0
    - numpy >=1.23.3
    - pycasreg >=0.1.0

test:
  imports:
    - pyecospold
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sami-m-g/pyecospold
  summary: A Python package that converts ecospold XML formats to their Python equivalents and export the same data back to XML.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
